### ISSUE TITLE
'nuke_util' folder is empty,module initialize error 

### ISSUE THREAD

**Issue by squallyaohao** [vinavfx/nuke_comfyui#5]
hi,'nuke_util' and 'python_util' folder are empyt,nuke pops up an error message when initialize this plugin says 'ModuleNotFoundError: No module named 'nuke_comfyui.nuke_util.nuke_util'

**Comment by vinavfx** [comment]
You have to clone the repository with 'recursive' so that it also clones the submodules: 

cd ~/.nuke
git clone --recursive https://github.com/vinavfx/nuke_comfyui.git
