### ISSUE TITLE
Getting the error "The system cannot find the path specified"

### ISSUE THREAD

**Issue by eidyk** [vinavfx/nuke_comfyui#6]
I have downloaded comfyui to my server and copied the nuke_comfyui folder to my .nuke directory in Windows 10. I have then installed the websocket client and added it's link in the menu.py file. However I'm getting the error:

```
Traceback (most recent call last):
  File "D:/Users/Knowlese/Documents/.nuke/menu.py", line 13, in <module>
    comfyui.setup()
  File "D:\Users/Knowlese/Documents/.nuke\nuke_comfyui\__init__.py", line 28, in setup
    for nk in os.listdir(nodes_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/Eidy/.nuke/nuke_comfyui\\nodes\\ComfyUI'
```

Do you know what this may be?

**Comment by eidyk** [comment]
Sorry I actually just fixed this by changing this line: `path = '{}/nuke_comfyui'.format(get_nuke_path())`

to `path = 'D:/Users/Knowlese/Documents/.nuke/nuke_comfyui'`

I moved my default nuke folder location!

**Comment by vinavfx** [comment]
I set an environment variable NUKE_USER so that there is no confusion.
https://github.com/vinavfx/nuke_comfyui/commit/2db3a1df327733a48da25f60d5b688e1107c02c9
